<?php

namespace ContentManagerBundle\ContentManagerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentTaxonomyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentTaxonomyRepository extends EntityRepository
{
}
